#define MS_CREATED @"created"
#define MS_TYPE @"type"
#define MS_DATA @"data"
#define MS_USER @"user"
#define MS_URL @"url"
#define MS_TEXT @"text"
#define MS_NAME @"name"
#define MS_COUNTRY @"country"
#define MS_TYPE_TEXT @"TEXT"
#define MS_TYPE_IMG @"IMG"
#define MS_NO_ENTRY @"No entry"
#define MS_INVALID_DATA @"Invalid data"